name: Lint

on: pull_request

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run build
